//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteLaptopServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLaptop
    {
        public int LaptopCode { get; set; }
        public string LaptopName { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<bool> FingerPrint { get; set; }
    }
}
